In [7]:
# The code is from https://github.com/ShusenTang/Dive-into-DL-PyTorch/blob/master/code/chapter02_prerequisite/2.2_tensor.ipynb
# This repo is for self study

In [1]:
import torch

torch.manual_seed(0)
torch.cuda.manual_seed(0)
print(torch.__version__)

1.3.0


### Create a tensor

In [2]:
# torch.empty() creates tensor with any data type you want
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 7.7052e+31],
        [1.9447e+31, 5.0207e+28, 2.3329e-18],
        [4.2330e+21, 7.2251e+28, 7.0368e+28],
        [3.3127e-18, 2.3336e-18, 4.5447e+30],
        [3.0750e+29, 1.9284e+31, 1.8891e+31]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.float64)     # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 指定新的数据类型
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6035,  0.8110, -0.0451],
        [ 0.8797,  1.0482, -0.0445],
        [-0.7229,  2.8663, -0.5655],
        [ 0.1604, -0.0254,  1.0739],
        [ 2.2628, -0.9175, -0.2251]])
